---
title: "Titi Monkeys"
Author: Audrey Tjahjadi
output: html_document
---

```{r}
#0<x<30,mean=15, range=31 (including 0)
#each possibility does NOT have equal chance of happening

proba2<-ppois(8, lambda=15, lower=FALSE)
proba2
```
```{r}
probb2<-ppois(0,lambda = 15)
#probability of hearing exactly 0 calls
probb2
```

```{r}
probc<-(1/31)
#probability of hearing exactly 3 calls
probc
```

```{r}
x <- 0:30
l = 15
probset <- dpois(x = x, lambda = l)
barplot(probset, names.arg = x, space = 0, xlab = "Number of Calls", ylab = "Probability", xlim = c(0, 30), col = "purple", main = "Probability Mass Function")
```
```{r}
library(manipulate)
outcomes<-(0:30)
manipulate(hist(sample(outcomes, n, replace = TRUE), breaks = seq(0, 30, 1), col = "purple", probability = TRUE, main = paste("Histogram of Outcomes of ", n, " Days of Listening", sep = ""), xlab = "Number of Calls", ylab = "probability", xlim = c(0,30), ylim = c(0, .09)), n = slider(0, 10000, initial = 104, step = 100))
#produces histogram showing results of 104 days recording 0 to 30 calls 
#histogram does not match Poisson distribution above
```
