---
title: "Zombies HW"
Author: Audrey Tjahjadi
output: html_document
---

```{r}
f<-"C:/Users/Audrey/Desktop/zombies.csv"
d<-read.csv(f)
head(d)
```

```{r}
muh<-(d$height)
meanh<-mean(muh)
meanh
varmuh <- function(muh) {
     sqrt(sum((muh - mean(muh))^2)/(length(muh)))
}
varmuh(muh)
```
```{r}
muw<-(d$weight)
meanw<-mean(muw)
meanw
varmuw <- function(muw) {
     sqrt(sum((muw - mean(muw))^2)/(length(muw)))
}
varmuw(muw)
```
```{r}
muy<-(d$years_of_education)
meany<-mean(muy)
meany
varmuy <- function(muy) {
     sqrt(sum((muy - mean(muy))^2)/(length(muy)))
}
varmuy(muy)
```
```{r}
muz<-(d$zombies_killed)
meanz<-mean(muz)
meanz
varmuz <- function(muz) {
     sqrt(sum((muz - mean(muz))^2)/(length(muz)))
}
varmuz(muz)
```
```{r}
mua<-(d$age)
meana<-mean(mua)
meana
varmua <- function(mua) {
     sqrt(sum((mua - mean(mua))^2)/(length(mua)))
}
varmua(mua)
```
```{r}
library(ggplot2)
p <- ggplot(data = d, aes(x = gender, y = height))
p <- p + geom_boxplot()
p <- p + theme(axis.text.x = element_text(angle = 90))
p <- p + ylab("Height")
p
```

```{r}
library(ggplot2)
p2 <- ggplot(data = d, aes(x = gender, y = weight))
p2 <- p2 + geom_boxplot()
p2 <- p2 + theme(axis.text.x = element_text(angle = 90))
p2 <- p2 + ylab("Weight")
p2
```

```{r}
library(ggplot2)
p3 <- ggplot(data = d, aes(x = gender, y = years_of_education))
p3 <- p3 + geom_boxplot()
p3 <- p3 + theme(axis.text.x = element_text(angle = 90))
p3 <- p3 + ylab("Years of Education")
p3
```

```{r}
library(ggplot2)
p4 <- ggplot(data = d, aes(x = gender, y = zombies_killed))
p4 <- p4 + geom_boxplot()
p4 <- p4 + theme(axis.text.x = element_text(angle = 90))
p4 <- p4 + ylab("Zombies Killed")
p4
```

```{r}
library(ggplot2)
p5 <- ggplot(data = d, aes(x = gender, y = age))
p5 <- p5 + geom_boxplot()
p5 <- p5 + theme(axis.text.x = element_text(angle = 90))
p5 <- p5 + ylab("Age")
p5
```

```{r}
library(ggplot2)

scatter<- ggplot(data = d, aes(x = age, y = weight)) 
scatter <- scatter + xlab("Age") + ylab("Weight")
scatter <- scatter + geom_point() 
scatter <- scatter + theme(legend.position = "bottom", legend.title = element_blank())  
scatter 

```
```{r}
scatter1<- ggplot(data = d, aes(x = age, y = height)) 
scatter1 <- scatter1 + xlab("Age") + ylab("Height")
scatter1 <- scatter1 + geom_point() 
scatter1 <- scatter1 + theme(legend.position = "bottom", legend.title = element_blank())  
scatter1 
```

```{r}
par(mfrow = c(2, 3))  #two panels
attach(d)
hist(muh, freq = FALSE, col = "purple", main = "Height")
hist(muw, freq = FALSE, col = "purple", main = "Weight")
hist(muy, freq = FALSE, col = "purple", main = "Years of Education")
hist(muz, freq = FALSE, col = "purple", main = "Zombies killed")
hist(mua, freq = FALSE, col = "purple", main = "Age")

#years of education and zombies killed do not follow the normal distribution. Their histograms resemble a Bernoulli distribution.  
```
```{r}
attach(d)
par(mfrow = c(2,3))
qqnorm(muh, main = "Q-Q Plot", xlab = "Height", plot.it = TRUE, datax = FALSE)
qqnorm(muw, main = "Q-Q Plot", xlab = "Weight", plot.it = TRUE, datax = FALSE)
qqnorm(muy, main = "Q-Q Plot", xlab = "Years", plot.it = TRUE, datax = FALSE)
qqnorm(muz, main = "Q-Q Plot", xlab = "Zombies", plot.it = TRUE, datax = FALSE)
qqnorm(mua, main = "Q-Q Plot", xlab = "Age", plot.it = TRUE, datax = FALSE)
```

```{r}
s<-d[sample(nrow(d), 30, replace = FALSE, prob = NULL), ]
#if replace = FALSE after () add , and one space close brackets
s
```

```{r}
library(sciplot)

s_h<-sample(d$height,size=30,replace=FALSE)
mean(s_h)
sd(s_h)
se(s_h)
upper_h<-mean(s_h)+qnorm(0.975,mean=0,sd=1)*se(s_h)
lower_h<-mean(s_h)+qnorm(0.025,mean=0,sd=1)*se(s_h)
ci_h<-c(lower_h,upper_h)
ci_h
```
```{r, eval = FALSE}
s_w <- sample(d$weight, size = 30, replace = FALSE) #does not want to knit past this point, could not find reason why, did not understande error message
mean(s_w)
s_wsd<-sd(s_w)
upper_w <- mean(s_w) + qnorm(0.975, mean = 0, sd = 1) * se(s_w)
lower_w <- mean(s_w) - qnorm(0.025, mean = 0, sd = 1) * se(s_w)
ci_w <- c(lower1, upper1)
ci_w

```
```{r}
#cannot assume normality for this as years of education did not show normality
s_y<-sample(d$years_of_education,size=30,replace=FALSE)
mean(s_y)
s_ysd<-sd(s_y)
```
```{r}
set<-NULL  # sets up a dummy variable to hold our simulations
n<-15
for (i in 1:10000) {
    set[i]<-mean(sample(s_y,n,replace=TRUE))
}
quantile(set,c(0.025,0.975))

```


```{r}
#cannot assume normality for this zombies killed as histogram did not show normality
s_z<-sample(d$zombies_killed,size=30,replace=FALSE)
mean(s_z)
sd(s_z)
```
```{r}
set<-NULL  # sets up a dummy variable to hold our simulations
n<-15
for (i in 1:10000) {
    set[i]<-mean(sample(s_z,n,replace=TRUE))
}
quantile(set,c(0.025,0.975))
```


```{r}
s_a<-sample(d$age,size=30,replace=FALSE)
mean(s_a)
s_asd<-sd(s_a)
upper_a<-mean(s_a)+qnorm(0.975,mean=0,sd=1)*se(s_a)
lower_a<-mean(s_a)+qnorm(0.025,mean=0,sd=1)*se(s_a)
ci_a<-c(lower_a,upper_a)
ci_a
```


```{r}
attach(d)
height2<-NULL
for (i in 1:100) {
    height2[i] <- mean(sample(d$height,30))
}
mean(height2)
sd(height2)
```
```{r}
weight2<-NULL
for (i in 1:100) {
    weight2[i] <- mean(sample(d$weight,30))
}
mean(weight2)
sd(weight2)
```

```{r}
edu2<-NULL
for (i in 1:100) {
    edu2[i] <- mean(sample(d$years_of_education,30))
}
mean(edu2)
sd(edu2)
```
```{r}
kill2<-NULL
for (i in 1:100) {
    kill2[i] <- mean(sample(d$zombies_killed,30))
}

mean(kill2)
sd(kill2)
```

```{r}
age2<-NULL
for (i in 1:100) {
    age2[i] <- mean(sample(d$age,30))
}

mean(age2)
sd(age2)
```